### ISSUE TITLE
Consider merging/using existing library

### ISSUE THREAD

**Issue by dpbevin** [Backbase/backbase-openapi-tools#10]
Have you considered merging with, or utilizing this existing library?
https://github.com/raml-org/webapi-parser
It's written in SCALA and provides output in both Java and JS form.
Just a thought.

**Comment by bartveenstra** [comment]
The backbase-openapi-tools are specially created for converting the specs of Backbase DBS Capabilities that are still written in RAML. Before writing this tool, I did try many out of the box converters from RAML to OAS but many of them didn't convert many aspects of our  RAML specs. 

Have you compared the output of boat and webapi-parser?

**Comment by dpbevin** [comment]
It was just a suggestion that might save you some work. If you've considered it then it's all good. I'm a big fan of DRY ;-)

**Comment by bartveenstra** [comment]
Absolutely! Same here! But due to the nature of our complicated RAML specs, I couldn't find a OOTB solution that worked. So ended up building my own and I am pretty satisfied how it turned out.
