### ISSUE TITLE
Release 0.14.2 - <serializableModel>true</serializableModel> appending comma(,) automatically in generated source

### ISSUE THREAD

**Issue by navinnagrani** [Backbase/backbase-openapi-tools#263]
Hi Team,
I am trying to generate source using above version i.e 0.14.2 , while I am putting 
`<configuration>
.....
<configOptions>
     <serializableModel>true</serializableModel>
</configOptions>
</configuration>`
in my pom.xml. I am doing mvn clean install to generate the source file from yaml spec. The source file is getting generated with implementing Serializable interface as well. But the problem is it is automatically appending comma after it which is giving me build failure and showing this error [31,4] illegal start of type. I am attaching a screenshot for the same for a more clearer picture.
Can someone please help me for this.
Thanks,
![8C4F306D-392A-44A8-A0BA-8212F864666E_1_201_a](https://user-images.githubusercontent.com/74898439/162004433-b2cd3cda-2ff4-4ef0-8fe1-2671cce00fc3.jpeg)

**Comment by sina-attarzadeh** [comment]
As a work around just add this to your schemas:

`x-implements:
        - java.io.Serializable`
