### ISSUE TITLE
get error when i try to consume spec openapi in service project backbase

### ISSUE THREAD

**Issue by amineitmaps** [Backbase/backbase-openapi-tools#471]
I'm following A tutorial in backbase academy exactly in "Backbase Backend Essentials Course - Service SDK and Direct Integration Services" and i get error when i try to consume specification from service project , this is the error

> exchange-rate-service: Compilation failure: Compilation failure: [ERROR] C:\Users\medamine\Desktop\retail-banking-training\direct-integration-services\exchange-rate-service\target\generated-sources\api\src\main\java\com\backbase\training\exchange\rate\api\service\v1\model\ExchangeRateItem.java:[49,96] error: cannot find symbol [ERROR] symbol: method requiredMode() [ERROR] location: @interface Schema

**Comment by jjjasper** [comment]
Hi there,

can you please share the spec version you are trying to use, the boat-plugin config that you have, and the dependencies from your pom file? (So basically: can you share your pom file)

**Comment by amineitmaps** [comment]
this is file pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.backbase.buildingblocks</groupId>
        <artifactId>backbase-openapi-spec-starter-parent</artifactId>
        <version>11.3.0</version>
    </parent>

    <groupId>com.backbase.training</groupId>
    <artifactId>exchange-rate-specification</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>Backbase :: Exchange Rate Specification</name>

    <properties>
        <!-- plugin versions -->
        <boat-maven-plugin.version>0.1.7</boat-maven-plugin.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>com.backbase.oss</groupId>
                <artifactId>boat-maven-plugin</artifactId>
                <version>${boat-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>boat-validation</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>validate</goal>
                        </goals>
                        <configuration>
                            <input>${project.basedir}/src/main/resources/openapi.yaml</input>
                            <failOnWarning>true</failOnWarning>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

```

**Comment by amineitmaps** [comment]
any solution for this problem , even with this project i get the same error
https://github.com/Backbase/documentation-code-samples/tree/master/service-sdk/11.0.0/create-openapi-spec-project
these is the steps that i followed : 
1.download project from github
2.run cmd "mvn clean install" on project "messaging-api"
until now i get BUILD SUCCESS
3. run cmd "mvn clean install" on project "messaging-service"
i get this error 

> ErrorItem.java:[67,3] error: cannot find symbol
> symbol:   class Schema
> location: class ErrorItem

**Comment by amineitmaps** [comment]
problem solved just upgrade dependency swagger-annotations from
<dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-annotations</artifactId>
      <version>1.6.0</version>
    </dependency>

To 

 <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-annotations</artifactId>
      <version>2.2.8</version>
    </dependency>

**Comment by jjjasper** [comment]
I was trying to reproduce your issue, and with success, however, I also noticed that the plugin giving you trouble was actually not the backbase open-api tool plugin (aka boat). The training is instructing to use openapitools plugin.

**Comment by amineitmaps** [comment]
Thank you for your interaction. It appears that the problem is not with the BOAT plugin, as I initially thought. I thought the problem was with the plugin.
