### ISSUE TITLE
Enum types are generated with "Enum" suffix

### ISSUE THREAD

**Issue by sfuenffinger** [Backbase/backbase-openapi-tools#61]
We have some types in our spec such as "Status" and "Type" which are currently being generated as "StatusEnum" and "TypeEnum".

It would be nice to be able to specify a name or have them generate without the suffix by default.

**Comment by pa314159** [comment]
It depends on how you define the enum.

When you inline the type definition, the generator picks a name for you.

But the best practice is to define the type in the "components/schemas" section and use $ref; this way you can use whatever name you want.

**Comment by sfuenffinger** [comment]
Do you have an example of how to do this? Eg. how to specify an exact name to be used for the generated class?

**Comment by pa314159** [comment]
Assuming everything it's in openapi.yaml
```
  status:
    $ref: '#/components/schemas/MyStatus'
```

then later under `components`
```
components:
  schemas:
    MyStatus:
      type: string
      description: The status of the event.
      enum:
      - Initiated
      - Successful
      - Failed
```

**Comment by bartveenstra** [comment]
@sfuenffinger  Can I mark this as resolved?

**Comment by bartveenstra** [comment]
Resolved
