### ISSUE TITLE
Regression: useBeanValidation broken from 

### ISSUE THREAD

**Issue by jjjasper** [Backbase/backbase-openapi-tools#633]
bean validations are no longer generated on Pojo's starting 0.17.5

generator: boat-spring

having open-api property definition
```
  state:
    maxLength: 50
    minLength: 1
    type: string
```

0.17.4 generates
```
  @lombok.Getter
  @lombok.Setter
  @lombok.EqualsAndHashCode.Include
  @lombok.ToString.Include

      @NotNull @Size(min = 1, max = 50) 
      private String externalStateId;
```

0.17.5 generates
```
  @lombok.Getter
  @lombok.Setter
  @lombok.EqualsAndHashCode.Include
  @lombok.ToString.Include

      private String externalStateId;
```

0.17.16 is still broken

**Comment by walaniam** [comment]
@jjjasper I've noticed that those contstraints are added on getters.

For such definition https://github.com/Backbase/backbase-openapi-tools/blob/main/boat-scaffold/src/test/resources/boat-spring/openapi.yaml#L201 there is following code being generated:
```java
    @NotNull @Size(min = 3, max = 251) 
    @Schema(name = "name", description = "Request name", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty("name")
  public String getName() {
  return name;
  }
```
Above code is tested here (with real validator) https://github.com/Backbase/backbase-openapi-tools/blob/main/boat-scaffold/src/test/java/com/backbase/oss/codegen/java/BoatSpringCodeGenTests.java#L219

**Comment by jjjasper** [comment]
If the annotations were generated on the getters, that did not work for me in a real service.
[This change](https://github.com/Backbase/backbase-openapi-tools/pull/632/commits/06ea2c308a6d48157bbb5f09081f64911b1a76df) fixes the behaviour for me.
